require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'

  TargetRubyVersion: 2.6
Rails:
  Enabled: true
Performance:
  Enabled: true
Style/Documentation:
  Enabled: false
