version: '3.9'
services:
  postgresql:
    image: postgres:13.4
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
    env_file: .env.development
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  dbdata:
