development: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  database: hobbies_app_development
  host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USER"] || 'postgres' %>
  password: <%= ENV["DB_PASSWORD"] || 'password' %>

test:
  <<: *default
  database: hobbies_app_test

production:
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>
